/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#e8f0ff",
        "on-error": "#ffffff",
        "surface-bright": "#f8f9ff",
        "on-tertiary-fixed": "#001c37",
        "on-secondary-fixed-variant": "#005049",
        "primary-container": "#1a6ebd",
        "on-tertiary-fixed-variant": "#07497d",
        "on-primary-fixed": "#001c39",
        "surface-dim": "#cbdbf5",
        "primary-fixed": "#d3e3ff",
        "tertiary-container": "#3d6fa6",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#d2e4ff",
        "on-secondary-container": "#006f66",
        "secondary-fixed": "#89f5e7",
        "secondary-fixed-dim": "#6bd8cb",
        "surface-tint": "#0060ab",
        "on-primary-fixed-variant": "#004882",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#213145",
        "tertiary": "#20568c",
        "tertiary-fixed-dim": "#a0c9ff",
        "on-error-container": "#93000a",
        "surface": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#0b1c30",
        "error-container": "#ffdad6",
        "background": "#f8f9ff",
        "outline-variant": "#c1c7d3",
        "inverse-on-surface": "#eaf1ff",
        "outline": "#717782",
        "surface-container-highest": "#d3e4fe",
        "on-surface-variant": "#414751",
        "on-secondary-fixed": "#00201d",
        "primary": "#005599",
        "surface-container-low": "#eff4ff",
        "secondary-container": "#86f2e4",
        "surface-container": "#e5eeff",
        "surface-variant": "#d3e4fe",
        "on-primary-container": "#e8efff",
        "on-primary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "primary-fixed-dim": "#a3c9ff",
        "inverse-primary": "#a3c9ff",
        "secondary": "#006a61",
        "error": "#ba1a1a",
        "on-background": "#0b1c30"
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-xl": "1.5rem",
        "space-2xl": "2rem",
        gutter: "1rem",
        "gutter-lg": "1.5rem",
        margin: "1rem",
        "margin-md": "1.5rem",
        "margin-lg": "2rem"
      },
      fontFamily: {
        "headline-sm": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "clinical-value-md": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "clinical-code": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        caption: ["Inter", "sans-serif"],
        "clinical-value-lg": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-sm": ["16px", { lineHeight: "24px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "clinical-value-md": ["14px", { lineHeight: "20px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "clinical-code": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
        caption: ["11px", { lineHeight: "16px", fontWeight: "500" }],
        "clinical-value-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
